"""
Django settings for PersonalWeb project.

Generated by 'django-admin startproject' using Django 2.2.2.

For more information on this file, see
https://docs.djangoproject.com/en/2.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/2.2/ref/settings/
"""

import os

# Build paths inside the project like this: os.path.join(BASE_DIR, ...)
BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/2.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = '5ilktohhk^zsn7@$e&9+c11@94xpcapam+pi3mdl_dd@6hd8nm'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []

# RSA密钥
# 公钥
RSA_PUBLIC_KEY = 'MIGfMA0GCSqGSIb3DQEBAQUAA4GNADCBiQKBgQCwKtpAUURVyqiuQvq4P7rD/6lK/wZxNFtkyR+gNEM3X7r79n0GxzR7ePaBU6sW0A/eLfAF4ePxRfKzxW7t9cfblXyEFIsxHWwbu5m3oBSYFP0d70s5asdqf+caXYoqACXOm336QVOd7O3Oz3Gwfvq7uhfSJ8NdyjG9o6VPvoUXFwIDAQAB'
# 私钥
RSA_PRIVATE_KEY = 'MIICXAIBAAKBgQCwKtpAUURVyqiuQvq4P7rD/6lK/wZxNFtkyR+gNEM3X7r79n0GxzR7ePaBU6sW0A/eLfAF4ePxRfKzxW7t9cfblXyEFIsxHWwbu5m3oBSYFP0d70s5asdqf+caXYoqACXOm336QVOd7O3Oz3Gwfvq7uhfSJ8NdyjG9o6VPvoUXFwIDAQABAoGBAKZ+6aTN6aq3jXKdBP5r5OTm1SZ3HqyREiuP1h8AJeLIzBzkGcf1L4neigMyg0ldPRH8EpRMqLTYKghzeWLW3pn9DckbsAGXUABeesp0E6dXdwpjCXrEakQEP5H/lq82DhS0+UXBI1BFSCl03X7FrN2P/1/Jy4LwfcHYnf1l2GVhAkEAz/yqJ7+1gXpB3z6vkEQGLhQEq93kd3Ho2osUsaEB2W5vdN7WPlCCBcMB8SwbXFWru25v5ongoe5A5qBzsNddxwJBANjVwc5v0E6z8280NJei3Dod00LCELe2w8TuBdk9Yce1Ie1TF8BVJBve5JJLEqPqzavnplrrNpa3whk1W3givDECQHoL4OlMRL0Cuc6/oRP95sZ5NriHj75LmIFNpcoKGeS2Oi8RaBTO901cPjKAWFnZZ9mnl4BnnepHvcvXkavO5RcCQBAgRZuewTU5ON+KWGb2m75OvYl3eVrQYtrggNrZL850cCOATIHnUxonh4RBxQ8fxVAFmF+mopau7+aEC1tx6eECQANJq5ONtdDLKCWzE6Vn7XyUkgisib59f+4GWT+122CAr4gNWaHpKKC4loT/pv/BbYxFW0HVuhJXL3QErwiq3YQ='

# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'frontend',
    'captcha',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'mysite.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'mysite.wsgi.application'


# Database
# https://docs.djangoproject.com/en/2.2/ref/settings/#databases

# 之后需要的是mysql，不需要SQLite
"""
DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': os.path.join(BASE_DIR, 'db.sqlite3'),
    }
}
"""
DATABASES = {
    'default': {
        'ENGINE' : 'django.db.backends.mysql',
        'NAME' : 'PersonalWebDB',
        'USER' : 'caproner',
        'PASSWORD' : 'pokemon7501085',
        'HOST' : 'localhost',
        'PORT' : '3306'
    }
}

# Password validation
# https://docs.djangoproject.com/en/2.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/2.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_L10N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/2.2/howto/static-files/

STATIC_URL = '/static/'
STATIC_ROOT = os.path.join(BASE_DIR, 'static')


# log setting
MAIN_LOG_FILE_PATH = os.path.join(BASE_DIR, "logs/main.log")
DJANGO_LOG_FILE_PATH = os.path.join(BASE_DIR, "logs/django.log")
MARKDOWN_LOG_FILE_PATH = os.path.join(BASE_DIR, "logs/markdown.log")

LOG_FORMAT = '\n'.join((
    '/' + '-' * 80,
    '[%(levelname)s][%(asctime)s][%(process)d:%(thread)d][%(filename)s:%(lineno)d %(funcName)s]:',
    '%(message)s',
    '-' * 80 + '/',
))

if DEBUG:
    MAIN_LOG_LEVEL = 'DEBUG'
else:
    MAIN_LOG_LEVEL = 'ERROR'

LOGGING = {
    'version': 1,
    'disable_existing_loggers': True,

    'formatters': {
        'standard': {
            'format': LOG_FORMAT,
        },
    },

    'filters': {
        'require_debug_false': {
            '()': 'django.utils.log.RequireDebugFalse'
        },
        'require_debug_true': {
            '()': 'django.utils.log.CallbackFilter',
            'callback': lambda x: DEBUG,
        }
    },
    'handlers': {
        'flylog': {
            'level': 'CRITICAL',
            'class': 'flylog.FlyLogHandler',
            'formatter': 'standard',
            'source': os.path.basename(os.path.dirname(os.path.dirname(os.path.abspath(__file__)))),
            'role_list': ['default'],
        },
        'main_file': {
            'level': MAIN_LOG_LEVEL,
            'class': 'logging.handlers.RotatingFileHandler',
            'filename': MAIN_LOG_FILE_PATH,
            'maxBytes': 1024*1024*500,
            'backupCount': 5,
            'formatter': 'standard',
            },
        'django_file': {
            'level': 'ERROR',
            'class': 'logging.handlers.RotatingFileHandler',
            'filename': DJANGO_LOG_FILE_PATH,
            'maxBytes': 1024*1024*500,
            'backupCount': 5,
            'formatter': 'standard',
        },
        'console': {
            'level': 'DEBUG',
            'filters': ['require_debug_true'],
            'class': 'logging.StreamHandler',
            'formatter': 'standard'
        },
        'maple_flylog': {
            'level': 'ERROR',
            'class': 'flylog.FlyLogHandler',
            'formatter': 'standard',
            'source': os.path.basename(os.path.dirname(os.path.dirname(os.path.abspath(__file__)))),
        },
        'markdown': {
            'level': MAIN_LOG_LEVEL,
            'class': 'logging.handlers.RotatingFileHandler',
            'filename': MARKDOWN_LOG_FILE_PATH,
            'maxBytes': 1024*1024*500,
            'backupCount': 5,
            'formatter': 'standard',
        }

    },
    'loggers': {
        'django': {
            'handlers': ['django_file', 'maple_flylog'],
            'level': 'DEBUG',
            'propagate': False
        },

        'django.request': {
            'handlers': ['console'],
            'level': 'DEBUG',
            'propagate': True,
        },
        'main': {
            'handlers': ['console', 'main_file', 'flylog'],
            'level': MAIN_LOG_LEVEL,
            'propagate': False
        },
        'MARKDOWN': {
            'handlers': ['console', 'markdown', 'flylog'],
            'level': MAIN_LOG_LEVEL,
            'propagate': False
        }
    }
}